title: Blessing Ohai
logo: assets/img/OHAI_BLESSING_HEADSHOT.jpg
description: [Email](ohai.blessing1@gmail.com) | [LinkedIn](linkedin.com/in/blessing-ohai-a1bb78203) | [GitHub](https://github.com/AnalystKemi)
theme: jekyll-theme-minimal
